# Lecture 2


## ndarray functions 

In [1]:
import numpy as np

a = np.zeros(5) #.zeros로 생성하면 float 형태로 생성
print(a.astype('int'))

b = np.zeros((2, 2)).astype('int')
print(b)

c = np.ones((4, 1)).astype('int')
print(c)

d = np.full(6, 3) #.full : 갯수, 채울 value
print(d)

e = np.full((3, 2), np.nan)
print(e)

[0 0 0 0 0]
[[0 0]
 [0 0]]
[[1]
 [1]
 [1]
 [1]]
[3 3 3 3 3 3]
[[nan nan]
 [nan nan]
 [nan nan]]


In [ ]:
a = np.arange(1, 100, 2)
a.shape = (10, 5) #.shape 메소드 : 변수.shape = (,)
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


### Exercise 1

In [ ]:
a = np.arange(1.5, 12, 2)
print(a)
b = a.reshape(2, 3)
print(b)
c = (b * 2).reshape(3, 2).astype('int')
print(c)

d = np.full(100, 'apple')
print(d)

[ 1.5  3.5  5.5  7.5  9.5 11.5]
[[ 1.5  3.5  5.5]
 [ 7.5  9.5 11.5]]
[[ 3  7]
 [11 15]
 [19 23]]
['apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple' 'apple'
 'apple']


In [ ]:
import numpy as np
import pandas as pd

a1 = [1, 2, 3, 4, 5]
a2 = [6, 7, 8, 9, 10]
data = np.array([a1, a2])
print(data)

print(data[:,2:4]) # start : end : step
print()
print(data[:,-2:-4:-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[3 4]
 [8 9]]

[[4 3]
 [9 8]]


In [ ]:
a3 = data[data>5]
a4 = np.where(data>5, data, 0)
print(a3)
print(a4)

#logical_and
a5 = np.logical_and(data>5, data < 7)
print(data[a5])

[ 6  7  8  9 10]
[[ 0  0  0  0  0]
 [ 6  7  8  9 10]]
[6]


In [2]:
import numpy as np
c1 = np.arange(1, 10).reshape(3, 3)
print(c1)
print()
print(c1[[1,2]]) # [1, 2]행만 출력 (리스트를 인자로 넣었다고 생각)
print()
print(c1[[1,2], 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[4 5 6]
 [7 8 9]]

[[5 6]
 [8 9]]


* Fancy Indexing
정수 / Boolean 값을 갖는 Numpy 배열로 배열을 인덱싱하는 기능



In [ ]:
c1[[0,1],[0,1]]
#(0, 0), (1, 1) 출력


array([1, 5])

In [ ]:
c1[[2, 1], [0, 1]]

array([7, 5])

In [3]:
c1[-1:0:-1, [0, 1]]

array([[7, 8],
       [4, 5]])

In [ ]:
c1[-2::-1, [1, 2]]

array([[5, 6],
       [2, 3]])

### Step : 1차원

In [ ]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [ ]:
print(a[::]) #전체 출력
print(a[::2]) #[1, 5, 9]
print(a[1::2]) #[3 7]
print(a[::-1]) #[9 7 5 3 1]
print(a[::-2]) #[9 5 1]
print(a[-2::-1]) #[7 5 3 1]
print(a[2::-1]) #[5 3 1]

[1 3 5 7 9]
[1 5 9]
[3 7]
[9 7 5 3 1]
[9 5 1]
[7 5 3 1]
[5 3 1]


### Indexing and Slicing in 2D array

In [ ]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
print("-"*15)
print(a[-1]) #[9 10 11 12]
print(a[0][-1]) # 4
print(a[0:2]) #[[1 2 3 4] [5 6 7 8]]
print(a[0:2][0]) #[1 2 3 4]
print(a[0:2][0][1:]) #[2 3 4]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------------
[ 9 10 11 12]
4
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[2 3 4]


In [ ]:
print(a[1::-1]) #[[5 6 7 8] [1 2 3 4]]
print(a[::2][1]) #[9 10 11 12]
print(a[::2][1:2]) #[[9 10 11 12]]
print(a[::2][::2]) #[[1 2 3 4]]

[[5 6 7 8]
 [1 2 3 4]]
[ 9 10 11 12]
[[ 9 10 11 12]]
[[1 2 3 4]]


### 시험 보기 전 꼭 보고 들어가기

In [ ]:
#역으로 코드 짜보기
print(a[::2, 1])
print(a[::2, 1:])
print(a[::2][1:])

[ 2 10]
[[ 2  3  4]
 [10 11 12]]
[[ 9 10 11 12]]


### Exercise 3 : Slicing

In [ ]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
print(a[:2, 1:4])  #
print(a[2:])
print(a[1, 0:2])   #
print(a[[1], 0:2]) #인자에 [](list) 형태로 넣으면 2차원 형태로 나옴

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3 4]
 [6 7 8]]
[[ 9 10 11 12]]
[[ 9 10 11 12]]
[5 6]
[[5 6]]


In [ ]:
print(a[1]) #1번째 행을 추출해서 돌려줌, 1차원
print(a[1:2]) #Slicing해서 그대로 돌려줌, 2차원

print("-"*14)
print(a[1, 0:1]) #1번째 행을 추출해서(1차원) 0번째 원소 돌려줌
print(a[1:2, 0:1]) #1번째 행 돌려줘서 0번째 출력 (2차원)
#index에 해당하는 배열 그대로 돌려줌

[5 6 7 8]
[[5 6 7 8]]
--------------
[5]
[[5]]


In [ ]:
a = np.arange(1, 13).reshape(3, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a[0:2, 1:4])
print(a[2])
print(a[2:])
print(a[:, :2])
print(a[1, :2])
print(a[1:2, 0:2])

[[2 3 4]
 [6 7 8]]
[ 9 10 11 12]
[[ 9 10 11 12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[5 6]
[[5 6]]


In [ ]:
print(a[0][1]) # 2
print(a[0,1])  # ** 0번째 행 1번째 원소 출력, 2 값만 출력**
print(a[[0,1]]) # [[1, 2, 3, 4] [5, 6, 7, 8]]
print(a[0:2][1]) # [[1 2 3 4] [5 6 7 8]]에서 1번째 행 추출, [5, 6, 7, 8]
print(a[0:2, 1]) # [[1, 2, 3, 4], [5, 6, 7, 8]]에서 1번째 원소 추출, [2 6]

2
2
[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]
[2 6]


In [ ]:
print(a[:][:-1]) 
'''
[[ 1  2  3  4] 
[ 5  6  7  8] 
[ 9 10 11 12]]
에서 (뒤에서 index가 1인) 1번째 행까지 출력 (2차원)
'''

print(a[:, :-1])
'''
[[ 1  2  3] 
[ 5  6  7] 
[ 9 10 11]]

뒤에서 index가 1인 열까지 출력 
'''

print(a[1, ])

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[5 6 7 8]


# Lecture 3

In [ ]:
b = np.arange(1, 9).reshape(2, 4)
b[0] = np.arange(4)
print(b)
b[0] = np.arange(12, 16)
print(b)

[[0 1 2 3]
 [5 6 7 8]]
[[12 13 14 15]
 [ 5  6  7  8]]


In [ ]:
b[0:1] = 4
print(b)
b[0:2] = np.arange(102, 110).reshape(2, 4)
print(b)

[[4 4 4 4]
 [5 6 7 8]]
[[102 103 104 105]
 [106 107 108 109]]
