In [1]:
import numpy as np
a = [6, 7.5, 8, 0, 1]
b = np.array(a)
print(b)
print(type(a))
print(type(b))
print(list(b))

[6.  7.5 8.  0.  1. ]
<class 'list'>
<class 'numpy.ndarray'>
[6.0, 7.5, 8.0, 0.0, 1.0]


In [ ]:
a * 2

[6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1]

In [2]:
b = np.array([1., 2, 3])
print(b*2)

[2. 4. 6.]


In [ ]:
b + b

array([12., 15., 16.,  0.,  2.])

In [ ]:
a = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(type(a))
b = np.array(a)
print(b)

<class 'list'>
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

(2, 4)

In [ ]:
np.array([(1, 2, 3, 4), (5, 6, 7, 8)])

(2, 4)

In [ ]:
np.array(([1, 2, 3, 4], [5, 6, 7, 8]))

(2, 4)

In [4]:
import numpy as np
a = 'abcd'
b = list(a)
c = tuple(a)
d = dict((('a', 1), ('b', 2)))
e = set(a)
print(d)

{'a': 1, 'b': 2}


In [ ]:
np.array(a)

array('abcd', dtype='<U4')

In [ ]:
f = np.array(b)
print(f.ndim)
f.shape = (2, 2)
print(f.ndim)
f.shape = (4, )
print(f.ndim)

1
2
1


In [ ]:
np.array(c)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [ ]:
np.array(d)

array({'a': 1, 'b': 2}, dtype=object)

In [ ]:
np.array(e)

array({'c', 'b', 'd', 'a'}, dtype=object)

In [ ]:
a = np.arange(1, 9).reshape(2, 4)
print(a.size)
print(a.shape)

8
(2, 4)


In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8]
b = list(np.array(a) * 10)
b

[10, 20, 30, 40, 50, 60, 70, 80]

In [ ]:
c = np.array(b)
c

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
c.shape = (2, 4)
c

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8 ]
b = np.array(a)
b.shape

(8,)

In [ ]:
b.shape = (1, 8)
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
a = np.array(a)
a.shape = (2, 4)
print(a + a)

[[ 2  4  6  8]
 [10 12 14 16]]
