In [ ]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.full((2, 5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full(2, 1)

array([1, 1])

In [ ]:
range(10)

range(0, 10)

In [ ]:
type(range(10))

range

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(np.arange(10))

numpy.ndarray

In [ ]:
np.arange(1., 3).dtype

dtype('float64')

In [ ]:
a = np.arange(1, 100, 2)
a.shape = (10, 5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [ ]:
a.reshape(5, 10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [2]:
import numpy as np
a = np.arange(1.5, 12, 2)
a

array([ 1.5,  3.5,  5.5,  7.5,  9.5, 11.5])

In [ ]:
b = np.arange(1.5, 12, 2).reshape(2, 3).astype('str')
b

array([['1.5', '3.5', '5.5'],
       ['7.5', '9.5', '11.5']], dtype='<U32')

In [ ]:
c = (a * 2).reshape(3, 2).astype('int')
c

array([[ 3,  7],
       [11, 15],
       [19, 23]])

In [ ]:
np.full(100, 'apple')

array(['apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'app

In [ ]:
a = np.arange(1, 7) # [1, 2, 3, 4, 5, 6]
print(a[5]) # 6
print(a[2:4]) # [3, 4]
a[5] = 12 
print(a) #[1, 2, 3, 4, 5, 12]

6
[3 4]
[ 1  2  3  4  5 12]


In [ ]:
a[1:3] = [14, 13]
print(a) #[1, 14, 13, 4, 5, 12]
a[1:3] = [12]
print(a) #[1, 12, 12, 4, 5, 12]
#a[1:3] = [14, 13, 12] #error

[ 1 14 13  4  5 12]
[ 1 12 12  4  5 12]


In [4]:
a = np.arange(1, 10, 2)
print(a) # [1, 3, 5, 7, 9]
print(a[::]) #동일
print(a[::2]) # [1, 5, 9]
print(a[::-2]) # [9, 5, 1]
print()
print(a[-2::-1]) # 앞의 -2 : 뒤에서 두 번째 의미
print(a[2::-1]) # [5, 3, 1]
print(a[-3::-1])

[1 3 5 7 9]
[1 3 5 7 9]
[1 5 9]
[9 5 1]

[7 5 3 1]
[5 3 1]
[5 3 1]


In [5]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
print(a[-1])    # a 행렬에서 가장 마지막 행을 출력해라 -> [9, 10, 11, 12]
print(a[0][-1]) # 0번째 행 마지막 원소 출력 -> [[4]]가 아니다!! 4
print(a[-1][0]) # 마지막 행 첫번째 원소 출력 -> 9
print()
print(a[0:2])   # 0 ~ 1행 출력 : 2차원 형태로 출력!!!
print(a[0:1])   # 0행 출력 : 2차원 형태로 동일하게 출력
print(a[0:2][0]) # 0행 출력 : 1차원 형태로 출력

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 9 10 11 12]
4
9

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]]
[1 2 3 4]


## 2차원 ndarray
ex. a = [[1, 2, 3, 4], 
         [5, 6, 7, 8]]

- a[0] -> [1, 2, 3, 4] : 0번째 행 출력, 1차원 형태로 출력
- a[0][0] -> 1 : 0번째 행 0번째 열 출력, 그냥 출력


## 2차원 배열에서의 Slicing

- a[0:2] -> [[1, 2, 3, 4], [5, 6, 7, 8]] : 2차원 배열 전체 출력
- a[0:2][0] -> [1, 2, 3, 4] : 1차원 형태로 출력
- a[0:2][0][1:] -> [2, 3, 4] : [1, 2, 3, 4] 중에서 1번째부터 끝까지 Slicing

In [ ]:
print(a[0:2][0][1:]) # [2, 3, 4]

[2 3 4]


In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
print(a[::2])  # 0번째 행부터 2 간격으로 출력, 이때 출력은 2차원
print(a[::-1]) # 행에 대해 역순으로 출력
print(a[1::-1]) # [[5, 6, 7, 8], [1, 2, 3, 4]]
print()
print(a[::2][1]) # [[1, 2, 3, 4], [9, 10, 11, 12]]에 대해 첫 행 -> (a[::2])[1] 개념으로 봐야함 -> 차원 하나 줄어듦

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[5 6 7 8]
 [1 2 3 4]]

[ 9 10 11 12]


In [ ]:
print(a[::2][::2]) # [[1, 2, 3, 4]] -> 이때는 2차원으로 나옴 (Slicing하면 차원에는 영향을 안 미침)

[[1 2 3 4]]


## Fancy Indexing