In [2]:
import numpy as np

b = np.arange(1, 9).reshape(2, 4)
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
b[0:2] = np.arange(102, 110).reshape(2, 4)
print(b)

[[102 103 104 105]
 [106 107 108 109]]


In [8]:
b[0:2, 0:2] = np.arange(15, 19).reshape(2, 2)
b

array([[15, 16,  4,  4],
       [17, 18,  4,  4]])

In [14]:
b[0:2, 0:2] = 16
b

array([[16, 16,  4,  4],
       [16, 16,  4,  4]])

In [15]:
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
d[[1, 3, 5]]

array([1, 3, 5])

In [18]:
d[[-1, -3, -5]] += 10
d

array([ 0,  1,  2,  3,  4, 15,  6, 27,  8, 29])

In [20]:
d[range(1, 10, 2)] *= 2
d

array([ 0,  2,  2,  6,  4, 30,  6, 54,  8, 58])

In [21]:
a = np.arange(0, 16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
a[[3, 0, 1]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [27]:
print(a[np.arange(4), 1:3])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [28]:
print(a[np.arange(4), 1:2])

[[ 1]
 [ 5]
 [ 9]
 [13]]


In [29]:
a[[0, 1, 2, 3][1, 3]]

TypeError: ignored

In [36]:
names = np.array([['a', 'b', 'c'],['d', 'a', 'f']])
names

array([['a', 'b', 'c'],
       ['d', 'a', 'f']], dtype='<U1')

In [37]:
names == 'a'

array([[ True, False, False],
       [False,  True, False]])

In [38]:
names[names == 'a']

array(['a', 'a'], dtype='<U1')

In [39]:
names[~(names == 'a')]

array(['b', 'c', 'd', 'f'], dtype='<U1')

In [40]:
# exercise

In [42]:
a = np.arange(1, 21).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
a[[0, 2], 0:5:2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [53]:
a[a%2 == 1] = 100
a

array([[100,   2, 100,   4, 100],
       [100, 100, 100, 100, 100],
       [100,  12, 100,  14, 100],
       [100, 100, 100, 100, 100]])