In [ ]:
a = 'abc'
a = list(a)
a[1] = 'a'
print(a)

['a', 'a', 'c']


In [6]:
import numpy as np
a = np.arange(7)
b = a
c = a[1:]
a

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
c

array([1, 2, 3, 4, 5, 6])

How to Copy?

In [9]:
a = np.arange(7)
b = a[[3, 2, 1]]  #3번, 2번, 1번 인덱스의 값을 fancy indexing
c = a.copy()
b 

array([3, 2, 1])

In [10]:
a = np.arange(32).reshape(8, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [11]:
a.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [12]:
a.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [13]:
x = np.array([1.1, 1.2, 1.3, 1.4])
y = np.array([2.1, 2.2, 2.3, 2.4])
condition = np.array([True, True, False, False])

np.where(condition, x, y)
#condition : True / False 로 출력하는 데이터
#True의 경우 x (첫번째 부분) / False의 경우 y (두번째 부분) 출력

array([1.1, 1.2, 2.3, 2.4])

In [14]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.where(a>7, np.nan, a)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [20]:
a = np.arange(16).reshape(4, 4)
a.sum(1)

array([ 6, 22, 38, 54])

In [22]:
a = np.arange(12).reshape(3, 4)
a.mean()

5.5

In [23]:
a.mean(0)

array([4., 5., 6., 7.])

In [24]:
a.min(0)

array([0, 1, 2, 3])

Calculation Function

In [25]:
a = np.arange(1, 7).reshape(2, 3)
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [26]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [30]:
a
np.append(a, 100) # 해당 ndarray의 끝에 값을 append함

array([  1,   2,   3,   4,   5,   6, 100])

In [29]:
np.append(a, a[1]) #a[1]인 [4, 5, 6]이 append됨

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [31]:
np.append(a, a[:, 1:]) # 2차원, 모든 column, index 1 이후의 배열 -> [[2, 3], [5, 6]]

array([1, 2, 3, 4, 5, 6, 2, 3, 5, 6])

In [32]:
a[:, 1:]

array([[2, 3],
       [5, 6]])

In [33]:
np.append(a, a[:, 1:].T, 1)

array([[1, 2, 3, 2, 5],
       [4, 5, 6, 3, 6]])

Exercise 1

In [40]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
np.append(a, a.sum(1).reshape(4, 1), 1)

array([[ 0,  1,  2,  3,  6],
       [ 4,  5,  6,  7, 22],
       [ 8,  9, 10, 11, 38],
       [12, 13, 14, 15, 54]])

In [44]:
np.append(a, a.sum(0).reshape(1, 4), 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [24, 28, 32, 36]])

In [47]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a.sort(); a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a[:, ::-1].sort(); a

array([[3, 2, 1],
       [6, 5, 4]])

In [51]:
#내림차순 정렬
a[::-1].sort(0);
a

array([[6, 5, 4],
       [3, 2, 1]])